/*
 typed.js - A JavaScript Typing Animation Library
   Author: Matt Boldt <me@mattboldt.com>
   Version: v2.0.6
   Url: https://github.com/mattboldt/typed.js
   License(s): MIT

*/
(function(h,e){"object"===typeof exports&&"object"===typeof module?module.exports=e():"function"===typeof define&&define.amd?define([],e):"object"===typeof exports?exports.Typed=e():h.Typed=e()})(this,function(){return function(h){function e(f){if(g[f])return g[f].exports;var k=g[f]={exports:{},id:f,loaded:!1};h[f].call(k.exports,k,k.exports,e);k.loaded=!0;return k.exports}var g={};e.m=h;e.c=g;e.p="";return e(0)}([function(h,e,g){Object.defineProperty(e,"__esModule",{value:!0});var f=function(){function d(a,
c){for(var b=0;b<c.length;b++){var d=c[b];d.enumerable=d.enumerable||!1;d.configurable=!0;"value"in d&&(d.writable=!0);Object.defineProperty(a,d.key,d)}}return function(a,c,b){c&&d(a.prototype,c);b&&d(a,b);return a}}(),k=g(1),l=g(3);g=function(){function d(a,c){if(!(this instanceof d))throw new TypeError("Cannot call a class as a function");k.initializer.load(this,c,a);this.begin()}f(d,[{key:"toggle",value:function(){this.pause.status?this.start():this.stop()}},{key:"stop",value:function(){this.typingComplete||
this.pause.status||(this.toggleBlinking(!0),this.pause.status=!0,this.options.onStop(this.arrayPos,this))}},{key:"start",value:function(){!this.typingComplete&&this.pause.status&&(this.pause.status=!1,this.pause.typewrite?this.typewrite(this.pause.curString,this.pause.curStrPos):this.backspace(this.pause.curString,this.pause.curStrPos),this.options.onStart(this.arrayPos,this))}},{key:"destroy",value:function(){this.reset(!1);this.options.onDestroy(this)}},{key:"reset",value:function(){var a=0>=arguments.length||
void 0===arguments[0]?!0:arguments[0];clearInterval(this.timeout);this.replaceText("");this.cursor&&this.cursor.parentNode&&(this.cursor.parentNode.removeChild(this.cursor),this.cursor=null);this.curLoop=this.arrayPos=this.strPos=0;a&&(this.insertCursor(),this.options.onReset(this),this.begin())}},{key:"begin",value:function(){var a=this;this.typingComplete=!1;this.shuffleStringsIfNeeded(this);this.insertCursor();this.bindInputFocusEvents&&this.bindFocusEvents();this.timeout=setTimeout(function(){a.currentElContent&&
0!==a.currentElContent.length?a.backspace(a.currentElContent,a.currentElContent.length):a.typewrite(a.strings[a.sequence[a.arrayPos]],a.strPos)},this.startDelay)}},{key:"typewrite",value:function(a,c){var b=this;this.fadeOut&&this.el.classList.contains(this.fadeOutClass)&&(this.el.classList.remove(this.fadeOutClass),this.cursor&&this.cursor.classList.remove(this.fadeOutClass));var d=this.humanizer(this.typeSpeed),e=1;!0===this.pause.status?this.setPauseStatus(a,c,!0):this.timeout=setTimeout(function(){c=
l.htmlParser.typeHtmlChars(a,c,b);var d=0,g=a.substr(c);if("^"===g.charAt(0)&&/^\^\d+/.test(g)){var f=1;g=/\d+/.exec(g)[0];f+=g.length;d=parseInt(g);b.temporaryPause=!0;b.options.onTypingPaused(b.arrayPos,b);a=a.substring(0,c)+a.substring(c+f);b.toggleBlinking(!0)}if("`"===g.charAt(0)){for(;"`"!==a.substr(c+e).charAt(0)&&!(e++,c+e>a.length););g=a.substring(0,c);f=a.substring(g.length+1,c+e);var h=a.substring(c+e+1);a=g+f+h;e--}b.timeout=setTimeout(function(){b.toggleBlinking(!1);c===a.length?b.doneTyping(a,
c):b.keepTyping(a,c,e);b.temporaryPause&&(b.temporaryPause=!1,b.options.onTypingResumed(b.arrayPos,b))},d)},d)}},{key:"keepTyping",value:function(a,c,b){0===c&&(this.toggleBlinking(!1),this.options.preStringTyped(this.arrayPos,this));c+=b;b=a.substr(0,c);this.replaceText(b);this.typewrite(a,c)}},{key:"doneTyping",value:function(a,c){var b=this;this.options.onStringTyped(this.arrayPos,this);this.toggleBlinking(!0);if(this.arrayPos===this.strings.length-1&&(this.complete(),!1===this.loop||this.curLoop===
this.loopCount))return;this.timeout=setTimeout(function(){b.backspace(a,c)},this.backDelay)}},{key:"backspace",value:function(a,c){var b=this;if(!0===this.pause.status)this.setPauseStatus(a,c,!0);else{if(this.fadeOut)return this.initFadeOut();this.toggleBlinking(!1);var d=this.humanizer(this.backSpeed);this.timeout=setTimeout(function(){c=l.htmlParser.backSpaceHtmlChars(a,c,b);var d=a.substr(0,c);b.replaceText(d);if(b.smartBackspace){var e=b.strings[b.arrayPos+1];e&&d===e.substr(0,c)?b.stopNum=c:
b.stopNum=0}c>b.stopNum?(c--,b.backspace(a,c)):c<=b.stopNum&&(b.arrayPos++,b.arrayPos===b.strings.length?(b.arrayPos=0,b.options.onLastStringBackspaced(),b.shuffleStringsIfNeeded(),b.begin()):b.typewrite(b.strings[b.sequence[b.arrayPos]],c))},d)}}},{key:"complete",value:function(){this.options.onComplete(this);this.loop?this.curLoop++:this.typingComplete=!0}},{key:"setPauseStatus",value:function(a,c,b){this.pause.typewrite=b;this.pause.curString=a;this.pause.curStrPos=c}},{key:"toggleBlinking",value:function(a){this.cursor&&
!this.pause.status&&this.cursorBlinking!==a&&(this.cursorBlinking=a,this.cursor.style.animationIterationCount=a?"infinite":0)}},{key:"humanizer",value:function(a){return Math.round(Math.random()*a/2)+a}},{key:"shuffleStringsIfNeeded",value:function(){this.shuffle&&(this.sequence=this.sequence.sort(function(){return Math.random()-.5}))}},{key:"initFadeOut",value:function(){var a=this;this.el.className+=" "+this.fadeOutClass;this.cursor&&(this.cursor.className+=" "+this.fadeOutClass);return setTimeout(function(){a.arrayPos++;
a.replaceText("");a.strings.length>a.arrayPos?a.typewrite(a.strings[a.sequence[a.arrayPos]],0):(a.typewrite(a.strings[0],0),a.arrayPos=0)},this.fadeOutDelay)}},{key:"replaceText",value:function(a){this.attr?this.el.setAttribute(this.attr,a):this.isInput?this.el.value=a:"html"===this.contentType?this.el.innerHTML=a:this.el.textContent=a}},{key:"bindFocusEvents",value:function(){var a=this;this.isInput&&(this.el.addEventListener("focus",function(c){a.stop()}),this.el.addEventListener("blur",function(c){a.el.value&&
0!==a.el.value.length||a.start()}))}},{key:"insertCursor",value:function(){this.showCursor&&!this.cursor&&(this.cursor=document.createElement("span"),this.cursor.className="typed-cursor",this.cursor.innerHTML=this.cursorChar,this.el.parentNode&&this.el.parentNode.insertBefore(this.cursor,this.el.nextSibling))}}]);return d}();e["default"]=g;h.exports=e["default"]},function(h,e,g){Object.defineProperty(e,"__esModule",{value:!0});var f=Object.assign||function(d){for(var a=1;a<arguments.length;a++){var c=
arguments[a],b;for(b in c)Object.prototype.hasOwnProperty.call(c,b)&&(d[b]=c[b])}return d},k=function(){function d(a,c){for(var b=0;b<c.length;b++){var d=c[b];d.enumerable=d.enumerable||!1;d.configurable=!0;"value"in d&&(d.writable=!0);Object.defineProperty(a,d.key,d)}}return function(a,c,b){c&&d(a.prototype,c);b&&d(a,b);return a}}(),l=(h=g(2))&&h.__esModule?h:{"default":h};h=function(){function d(){if(!(this instanceof d))throw new TypeError("Cannot call a class as a function");}k(d,[{key:"load",
value:function(a,c,b){a.el="string"===typeof b?document.querySelector(b):b;a.options=f({},l["default"],c);a.isInput="input"===a.el.tagName.toLowerCase();a.attr=a.options.attr;a.bindInputFocusEvents=a.options.bindInputFocusEvents;a.showCursor=a.isInput?!1:a.options.showCursor;a.cursorChar=a.options.cursorChar;a.cursorBlinking=!0;a.elContent=a.attr?a.el.getAttribute(a.attr):a.el.textContent;a.contentType=a.options.contentType;a.typeSpeed=a.options.typeSpeed;a.startDelay=a.options.startDelay;a.backSpeed=
a.options.backSpeed;a.smartBackspace=a.options.smartBackspace;a.backDelay=a.options.backDelay;a.fadeOut=a.options.fadeOut;a.fadeOutClass=a.options.fadeOutClass;a.fadeOutDelay=a.options.fadeOutDelay;a.isPaused=!1;a.strings=a.options.strings.map(function(a){return a.trim()});a.stringsElement="string"===typeof a.options.stringsElement?document.querySelector(a.options.stringsElement):a.options.stringsElement;if(a.stringsElement&&(a.strings=[],a.stringsElement.style.display="none",c=Array.prototype.slice.apply(a.stringsElement.children),
b=c.length))for(var d=0;d<b;d+=1)a.strings.push(c[d].innerHTML.trim());a.strPos=0;a.arrayPos=0;a.stopNum=0;a.loop=a.options.loop;a.loopCount=a.options.loopCount;a.curLoop=0;a.shuffle=a.options.shuffle;a.sequence=[];a.pause={status:!1,typewrite:!0,curString:"",curStrPos:0};a.typingComplete=!1;for(d in a.strings)a.sequence[d]=d;a.currentElContent=this.getCurrentElContent(a);a.autoInsertCss=a.options.autoInsertCss;this.appendAnimationCss(a)}},{key:"getCurrentElContent",value:function(a){return a.attr?
a.el.getAttribute(a.attr):a.isInput?a.el.value:"html"===a.contentType?a.el.innerHTML:a.el.textContent}},{key:"appendAnimationCss",value:function(a){if(a.autoInsertCss&&a.showCursor&&a.fadeOut){var c=document.createElement("style");c.type="text/css";var b="";a.showCursor&&(b+="\n        .typed-cursor{\n          opacity: 1;\n          animation: typedjsBlink 0.7s infinite;\n          -webkit-animation: typedjsBlink 0.7s infinite;\n                  animation: typedjsBlink 0.7s infinite;\n        }\n        @keyframes typedjsBlink{\n          50% { opacity: 0.0; }\n        }\n        @-webkit-keyframes typedjsBlink{\n          0% { opacity: 1; }\n          50% { opacity: 0.0; }\n          100% { opacity: 1; }\n        }\n      ");
a.fadeOut&&(b+="\n        .typed-fade-out{\n          opacity: 0;\n          transition: opacity .25s;\n          -webkit-animation: 0;\n                  animation: 0;\n        }\n      ");0!==c.length&&(c.innerHTML=b,document.head.appendChild(c))}}}]);return d}();e["default"]=h;h=new h;e.initializer=h},function(h,e){Object.defineProperty(e,"__esModule",{value:!0});e["default"]={strings:["These are the default values...","You know what you should do?","Use your own!","Have a great day!"],stringsElement:null,
typeSpeed:0,startDelay:0,backSpeed:0,smartBackspace:!0,shuffle:!1,backDelay:700,fadeOut:!1,fadeOutClass:"typed-fade-out",fadeOutDelay:500,loop:!1,loopCount:Infinity,showCursor:!0,cursorChar:"|",autoInsertCss:!0,attr:null,bindInputFocusEvents:!1,contentType:"html",onComplete:function(e){},preStringTyped:function(e,f){},onStringTyped:function(e,f){},onLastStringBackspaced:function(e){},onTypingPaused:function(e,f){},onTypingResumed:function(e,f){},onReset:function(e){},onStop:function(e,f){},onStart:function(e,
f){},onDestroy:function(e){}};h.exports=e["default"]},function(h,e){Object.defineProperty(e,"__esModule",{value:!0});var g=function(){function e(e,d){for(var a=0;a<d.length;a++){var c=d[a];c.enumerable=c.enumerable||!1;c.configurable=!0;"value"in c&&(c.writable=!0);Object.defineProperty(e,c.key,c)}}return function(f,d,a){d&&e(f.prototype,d);a&&e(f,a);return f}}(),f=function(){function e(){if(!(this instanceof e))throw new TypeError("Cannot call a class as a function");}g(e,[{key:"typeHtmlChars",value:function(e,
d,a){if("html"!==a.contentType)return d;a=e.substr(d).charAt(0);if("<"===a||"&"===a){for(a="<"===a?">":";";e.substr(d+1).charAt(0)!==a&&!(d++,d+1>e.length););d++}return d}},{key:"backSpaceHtmlChars",value:function(e,d,a){if("html"!==a.contentType)return d;a=e.substr(d).charAt(0);if(">"===a||";"===a){for(a=">"===a?"<":"&";e.substr(d-1).charAt(0)!==a&&!(d--,0>d););d--}return d}}]);return e}();e["default"]=f;f=new f;e.htmlParser=f}])});